pagina_ayuda:
    path:   /ayuda
    defaults: {_controller:OfertaBundle:Default:ayuda}
    
pagina_estatica:
    path:       /pagina/{pagina}
    defaults:   {_controller:OfertaBundle:Sitio:estatica}
usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /

tienda:
    resource: "@TiendaBundle/Resources/config/routing.yml"
    prefix:   /

ciudad:
    resource: "@CiudadBundle/Resources/config/routing.yml"
    prefix:   /

oferta:
    resource: "@OfertaBundle/Resources/config/routing.yml"
    prefix:   /

